// AUTO-GENERATED by scripts/optimize-landing-images.mjs — do not edit by hand.
// Maps a landing image src (exactly as components reference it) to a WebP
// srcset string. Regenerate after adding/replacing landing images.
export const LANDING_IMAGE_SRCSET: Record<string, string> = {
  "/hero/hero-direct-identity.png": "/hero/hero-direct-identity.w480.webp 480w, /hero/hero-direct-identity.w928.webp 928w",
  "/hero/hero-perform-anywhere.png": "/hero/hero-perform-anywhere.w480.webp 480w, /hero/hero-perform-anywhere.w768.webp 768w",
  "/hero/hero-2.png": "/hero/hero-2.w480.webp 480w, /hero/hero-2.w933.webp 933w",
  "/hero/hero-colors.png": "/hero/hero-colors.w480.webp 480w, /hero/hero-colors.w960.webp 960w",
  "/hero/hero-7.png": "/hero/hero-7.w480.webp 480w, /hero/hero-7.w960.webp 960w, /hero/hero-7.w1440.webp 1440w",
  "/landing/step-reference.jpg": "/landing/step-reference.w480.webp 480w, /landing/step-reference.w800.webp 800w",
  "/landing/step-final.jpg": "/landing/step-final.w480.webp 480w, /landing/step-final.w800.webp 800w",
  "/spin-demo.jpg": "/spin-demo.w480.webp 480w, /spin-demo.w717.webp 717w",
  "/josh/josh-pink-mic-portrait.jpg": "/josh/josh-pink-mic-portrait.w480.webp 480w, /josh/josh-pink-mic-portrait.w564.webp 564w",
  "/videos/landing-demo-reel-poster.jpg": "/videos/landing-demo-reel-poster.w480.webp 480w, /videos/landing-demo-reel-poster.w720.webp 720w",
  "/__l5e/assets-v1/586d8437-b8af-4663-bce9-9ac8c348e409/josh-blue-orange.jpg": "/josh/slideshow/josh-blue-orange.w480.webp 480w, /josh/slideshow/josh-blue-orange.w960.webp 960w",
  "/__l5e/assets-v1/a577d008-279d-4652-8d24-dcd2057c5c68/josh-slide-03.jpeg": "/josh/slideshow/josh-slide-03.w480.webp 480w, /josh/slideshow/josh-slide-03.w768.webp 768w",
  "/__l5e/assets-v1/d592b0f2-c04b-498f-ab61-675923515b48/josh-slide-04.jpeg": "/josh/slideshow/josh-slide-04.w480.webp 480w, /josh/slideshow/josh-slide-04.w960.webp 960w",
  "/__l5e/assets-v1/7d775117-69ff-4ae3-a4e6-111cfda9fe00/josh-slide-06.png": "/josh/slideshow/josh-slide-06.w480.webp 480w, /josh/slideshow/josh-slide-06.w960.webp 960w, /josh/slideshow/josh-slide-06.w1122.webp 1122w",
  "/__l5e/assets-v1/fcd904bd-6fdb-472c-892d-68d244f8d2cd/josh-slide-07.png": "/josh/slideshow/josh-slide-07.w480.webp 480w, /josh/slideshow/josh-slide-07.w960.webp 960w",
  "/__l5e/assets-v1/050fb9ad-f877-4b47-a7d1-bcead987e7a3/josh-slide-08.png": "/josh/slideshow/josh-slide-08.w480.webp 480w, /josh/slideshow/josh-slide-08.w960.webp 960w",
  "/__l5e/assets-v1/4e025110-9281-4805-9f1e-005d64b9c2f1/josh-slide-10.png": "/josh/slideshow/josh-slide-10.w480.webp 480w, /josh/slideshow/josh-slide-10.w960.webp 960w, /josh/slideshow/josh-slide-10.w1216.webp 1216w"
};
