-- Keep a small undo history for admin-managed site copy.
--
-- History stores the value that was active immediately before an upsert.
-- The service-role server functions are the only access path.

create table if not exists public.site_copy_history (
  id         bigint generated by default as identity primary key,
  key        text        not null,
  value      text        not null,
  changed_by uuid        not null references auth.users(id) on delete restrict,
  changed_at timestamptz not null default now()
);

create index if not exists site_copy_history_key_changed_at_idx
  on public.site_copy_history (key, changed_at desc, id desc);

alter table public.site_copy_history enable row level security;
revoke all on table public.site_copy_history from anon;
revoke all on table public.site_copy_history from authenticated;